apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-kafka-local-sa
  namespace: argo-kafka-local
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-kafka-local-role
  namespace: argo-kafka-local
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
  - apiGroups:
      - ''
    resources:
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflowtemplates
      - workfloweventbindings
      - clusterworkflowtemplates
      - cronworkflows
      - sensors
      - workflowtaskresults
      - eventsources
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-kafka-local-role-binding
  namespace: argo-kafka-local
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-kafka-local-role
subjects:
  - kind: ServiceAccount
    name: argo-kafka-local-sa
    namespace: argo-kafka-local
